---
description: Erro do Compilador CS0156
title: Erro do Compilador CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: 443bbc8287c860e0db11a228738e63077c2778c7
ms.sourcegitcommit: 5b475c1855b32cf78d2d1bbb4295e4c236f39464
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 09/24/2020
ms.locfileid: "91160262"
---
# <a name="compiler-error-cs0156"></a>Erro do Compilador CS0156

Uma instrução Throw sem argumentos não é permitida em uma cláusula finally que esteja aninhada dentro da cláusula catch de circunscrição mais próxima  
  
 Uma instrução [throw](../language-reference/keywords/throw.md) sem parâmetros só pode aparecer em uma cláusula **Catch** que não aceite parâmetros.  
  
 Para obter mais informações, consulte [exceções e tratamento de exceções](../programming-guide/exceptions/index.md).  
  
 O exemplo a seguir gera CS0156:  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
