---
description: "Saiba mais sobre: ' Catch ' não pode aparecer fora de uma instrução ' Try '"
title: "'Catch' não pode aparecer fora de uma instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 4ac18a51602c7dc5c4d7b397e1b64f9ed77fcc87
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473895"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' não pode aparecer fora de uma instrução 'Try'

`Catch` deve aparecer dentro de um `Try...Catch...Finally` bloco de instruções. Você tem uma instrução desnecessária `Catch` em seu `Try` bloco ou sua `Catch` instrução aparece fora dos limites de seu `Try` bloco correspondente.  
  
 **ID do erro:** BC30380  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1. Exclua a `Catch` instrução se ela for desnecessária ou coloque-a em um `Try...Catch...Finally` bloco de instruções.  
  
## <a name="see-also"></a>Consulte também

- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
