---
description: 'Saiba mais sobre: System. IdentityModel. IdentityModelAsyncCallbackThrewException'
title: System.IdentityModel.IdentityModelAsyncCallbackThrewException
ms.date: 03/30/2017
ms.assetid: e4fc924f-3b9e-44f5-97e4-b3a4bb855d89
ms.openlocfilehash: 304cf448b71c6a0aa901a09273b81b686020d0f2
ms.sourcegitcommit: ddf7edb67715a5b9a45e3dd44536dabc153c1de0
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/06/2021
ms.locfileid: "99635279"
---
# <a name="systemidentitymodelidentitymodelasynccallbackthrewexception"></a>System.IdentityModel.IdentityModelAsyncCallbackThrewException

System.IdentityModel.IdentityModelAsyncCallbackThrewException  
  
## <a name="description"></a>Descrição  

 Um retorno de chamada assíncrono gerou uma exceção.  
  
## <a name="see-also"></a>Consulte também

- [Rastreamento](index.md)
- [Utilizando o rastreamento para solucionar problemas em seu aplicativo](using-tracing-to-troubleshoot-your-application.md)
- [Administração e diagnósticos](../index.md)
